### PR TITLE
Update for google-datastore.js

### PR DESCRIPTION
**Pull request by saivittalb**

### CODE REVIEW

**Comment by raju249** [comment]
@saivittalb Thanks for you PR, but I think if you run a linter on the code, it would be same again as before as per the mentioned standard.
You can look up to adding more services of GCP to nodecloud-gcp-plugin

**Comment by saivittalb** [comment]
No, I was just browsing through and did some changes randomly on seeing the code.... Nothing more than that! You can close this PR if you want! :)

**Comment by rajikaimal** [comment]
FYI :) you can't just randomly edit code and hope it'll follow the standards or work properly.

**Comment by saivittalb** [comment]
> FYI :) you can't just randomly edit code and hope it'll follow the standards or work properly.

Thanks for info but I think so this code just works fine though I randomly found it! Tbh, I didn't even try to make a change to this PR but I still didn't even know why I did it! I did that when I joined GitHub..... I was a noob back 20 days on GitHub! That's all!

**Pull request closed without merging**
